spring.application.name=financeService
spring.datasource.url=jdbc:sqlite:src/main/resources/persistence/financePersistence.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.datasource.username=facoffee
spring.datasource.password=facoffee

# Informa ao Hibernate como traduzir os comandos SQL especificamente para a linguagem do SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# Cria automaticamente as tabelas no banco com base nas suas classes Java (Entidades)
#spring.jpa.hibernate.ddl-auto=update
# Mostra no console os comandos SQL que o Spring está executando (ótimo para aprender/testar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true